Feat/chain switcher implemented
monet-work/monet-web3 pull request #42
Opened 2024-06-17 11:49 UTC by Nainish-Rai

# Pull Request Template

## Description

Check whether the user have connected to base sepolia or not, if not then a popup will appear for user to change the chain

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so others can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Screenshots (if applicable)
![image](https://github.com/monet-work/monet-web3/assets/109546113/e0ac4e8a-4243-4b43-b4c2-70d78a86ea2e)

## Additional Context

Add any other context or screenshots about the feature request here.

2024-06-17 23:59 UTC, arindam-monet commented on components/chain-switcher.tsx
> +  setActiveChainChanged: any;
change the type to () => boolean instead of any

2024-06-18 00:04 UTC, arindam-monet commented on components/customer-dashboard.tsx
> +    any | null
can we avoid using the any type unless there is a valid reason?

2024-06-18 00:08 UTC, arindam-monet commented on context/auth-context.tsx
> +  const switchChain = useSwitchActiveWalletChain();
this seems to be duplicate. This statement appears in line 57 as well.
Also this this hook seems unused in auth-context.tsx.

2024-06-18 00:09 UTC, arindam-monet requested changes
please resolve the PR comments

2024-06-18 00:12 UTC, arindam-monet commented on components/customer-dashboard.tsx
> +  const fetchOnChainPointsForAllTokens = async () => {
I believe there is another PR for fetching the customer's on-chain points. Then why is this part of this PR as well?

2024-06-18 00:16 UTC, arindam-monet commented on app/(pages)/marketplace/page.tsx
> +            data={
why this has changes related to marketplace?

2024-06-18 06:09 UTC, anujkmonetwork requested changes

2024-06-18 06:09 UTC, anujkmonetwork commented on context/auth-context.tsx
> +    // console.log(chainId, baseSepolia, chainId.id === baseSepolia.id);
Remove this log.

2024-06-18 06:09 UTC, anujkmonetwork commented on context/auth-context.tsx
> +      console.log(
Remove this log.

2024-06-18 06:09 UTC, anujkmonetwork commented on components/chain-switcher.tsx
> +              We have detected you are using a different chain. Please switch to
You’re on a different network. Switch to **BaseSepolia** to keep going. 🚀
Change text to this

2024-06-18 06:09 UTC, anujkmonetwork commented on components/chain-switcher.tsx
> +                  Switch to Base Sepolia
Connect to **Base Sepolia!** 🌟
Change text to this.

2024-06-18 06:54 UTC, merged